## 异步编程
- 回调函数
- Promise
- async await
- generator

## 任务
#### 同步任务

#### 异步任务
- 微任务
  Promise.then process.nextTick
- 宏任务
  script setTimeout/setInterval

#### 事件循环 EvenLoop

## Promise
#### 1.基本知识
##### 结构
const promise = new Promise( (resolve,reject) => {异步操作} ).then()

1. Promise构造函数的参数是一个函数,函数的参数是两个方法resolve,reject
2. 异步操作完毕后,用resolve/reject函数改变promise实例的状态
3. resolve函数将Promise对象的状态:未完成-->成功
4. reject函数将Promise对象的状态从:未完成-->失败

##### 作用
拯救回调地狱
增强可读性

##### 状态
- 进行中:pending
- 已成功:fulfilled
- 已失败:rejected
  
##### 特点
- promsie对象的状态一旦从进行中变为其他状态,就不能再改变了
- 对象的状态不受外界任何的影响,只有异步操作的结果可以决定promise的状态

##### 缺点
- 一旦创建，就无法取消
- 如果不设置回调函数,promise内部的错误不会被抛出
- 当处于pending状态时,无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）

##### 过程
- throw抛出错误会阻塞后续执行
- resolve()/reject()不会阻塞后续执行,return会停止
  
#### 2.实例方法

promise
.then(result => {···})
.catch(error => {···})
.finally(() => {···});

- Promise.prototye.then()
  1. 参数:两个回调函数,对应resolve/reject状态
  2. 返回值:一个新的promise对象,后面还可以接then链式写法
  3. 用于为promise对象的两个状态的改变**注册回调函数**,这个回调函数属于**微任务**

- Promise.prototye.catch()
  1. 参数:处理错误的回调函数
  2. 返回值:一个失败的promise
  3. 是.then(null/undefined,err)的缩写,一般来说，使用catch方法代替then()第二个参数
  4. 用于发生错误的时候:reject状态/resolve发生错误时

- Promise.prototye.finally()
  1. 参数:不接受参数,不受上面结果影响
  2. 无论如何都会执行的方法,位置不要放在靠前
  
#### 3.构造函数方法
- Promise.resolve()
  1. 不同参数对应不同返回值
   - 没有参数 返回一个resolved状态的 Promise 对象
   - 参数是Promsie实例 不做任何改变原封不动的返回这个实例
   - 参数是不是Promise实例 返回一个resolved状态的 Promise 对象
  2. 让promise对象进入resolve状态
  3. new Promise((resolve,reject) => { resolve('foo'); })

- Promise.reject()
  1. 返回值是一个promise对象
  2. 让promise对象进入reject状态
  3. new Promise((resolve, reject) => reject('出错了'))

- Promise.all()
  1. Promise.all([promise1,promise2,promise3]).then()
  2. 用于处理**并行任务**
  3. **当遇到发送多个请求并根据请求顺序获取和使用数据的场景**/汇报所有请求结果
  4. 参数状态都成功对象的状态才是成功,有一个失败则对象状态为失败
  5. 结果成功的时候是回调函数的参数也是一个数组，这个数组按顺序保存着每一个promise对象resolve状态执行时的值。
  6. 结果失败的时候返回返回最先被reject失败状态的值。
  
- Promise.race()
  1. Promise.race([p1,p2,p3]).then()
  2. 只要p1、p2、p3之中有一个实例率先改变状态，promise对象的状态就跟着改变
  3. 率先改变的Promise实例的返回值则传递给promise对象的回调函数
  4. **当要做一件事，超过多长时间就不做了**/图片请求超时


#### 4.创建Promise的方式
- new Promise()
- Promise.resolve()
- Promise.reject()

#### 5.抛出异常throw
- Promise对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止
- 没有回调函数则错误无法抛出外层代码

new Promise((resolve,reject) => {
  throw new Error('err');
}).then(() => {
  throw new Error('err');
},(err) =>{
  throw new Error('err');
}).catch((err) => {

})

1. 构造函数抛出错误
  - 没有catch:进入then的reject处理函数,实例状态变为fullfilled
  - 有catch:进入then的reject处理函数,实例状态变为fullfilled

2. then的reject处理函数中抛出错误
   - 没有catch:错误被抛到全局,实例状态变为rejected
   - 有catch:被catch捕获到，状态变为fullfilled

3. then的resolve处理函数中抛出错误
   - 没有catch:错误被抛到全局,实例状态变为rejected
   - 有catch:被catch捕获到，状态变为fullfilled

Promise.reject():抛出异常
catch():异常处理
try...catch

#### 6. Promise中的then第二个参数和catch的区别
处理范围/作用
- 如果在then的resolve处理函数中抛出错误，后面的catch能捕获到，而then的第二个函数捕获不到
- promise内部报错，reject抛出错误后，捕获错误遵循**就近原则**


## async await
####  基本知识
##### 作用
##### 特点

#### async
#### await
#### 异常处理
#### async defer区别